### ISSUE TITLE
ReferenceError: SERVER is not defined

### ISSUE THREAD

**Issue by tintoverano** [alidcastano/rogue#27]
hi,

0.1.9 build results in the following error
````
ReferenceError: SERVER is not defined
    at Object.<anonymous> (.../node_modules/rogue/scripts/dev.js:16:31)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)
````
0.1.6 is OK

thanks,

tinto

**Comment by alidcastano** [comment]
Yea those were experimental publishes, sorry about that


The official first release is 0.2.4

**Comment by tintoverano** [comment]
works now, no worries :)
thanks!!
